import { TbNetwork } from "react-icons/tb";
import { IoLogOut, IoPieChartSharp } from "react-icons/io5";
import { MdDashboard } from "react-icons/md";
import { HiBellAlert } from "react-icons/hi2";
import { BsCpuFill } from "react-icons/bs";
import { BiSolidReport } from "react-icons/bi";
import { RiMenu5Line } from "react-icons/ri";
import { IoMdClose } from "react-icons/io";
export const iCON_TRAFFIC = <TbNetwork />;
export const ICON_CHART = <IoPieChartSharp />;
export const ICON_IDS = <BsCpuFill />;
export const ICON_REPORT = <BiSolidReport />;
export const ICON_ALERT = <HiBellAlert />;
export const ICON_DASHBOARD = <MdDashboard />;
export const ICON_MENU = <RiMenu5Line />;
export const ICON_LOGOUT = <IoLogOut />;
export const ICON_CLOSE = <IoMdClose />;
